# Generated by Django 4.0.4 on 2022-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_useraccount_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
