# Generated by Django 4.0.4 on 2022-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_useraccount_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high',
            field=models.CharField(choices=[('50-100cm', '50-100cm'), ('100cm +', '100cm +'), ('0-50cm', '0-50cm')], default='0-50cm', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_plant',
            field=models.CharField(choices=[('ZIMZELANA', 'ZIMZELANA'), ('LISTOPADNA', 'LISTOPADNA')], default='LISTOPADNA', max_length=20),
        ),
    ]
