# Generated by Django 4.0.4 on 2022-10-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_high_product_type_of_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plantcategory'),
        ),
    ]
