# Generated by Django 4.0.4 on 2022-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_plantcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='name',
            field=models.CharField(choices=[('Lekovito Bilje', 'Lekovito Bilje'), ('Cvetnice', 'Cvetnice'), ('Bobicasto Voce', 'Bobicasto Voce'), ('Sobno Svece', 'Sobno Svece'), ('Penjacice', 'Penjacice'), ('Zelena Biljka', 'Zelena Biljka')], default='Zelena Biljka', max_length=20),
        ),
    ]
