# Generated by Django 4.0.4 on 2022-05-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LB', 'Lekovito Bilje'), ('CV', 'Cvetnice'), ('BV', 'Bobicasto Voce'), ('SC', 'Sobno Svece'), ('PE', 'Penjacice'), ('ZE', 'Zelena Biljka')], default='ZE', max_length=2),
        ),
    ]
