# Generated by Django 4.0.4 on 2022-05-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_color_product_flowering_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Crna', 'CRNA'), ('Plava', 'PLAVA'), ('Roza', 'ROZA'), ('Crvena', 'CRVENA'), ('Sarena', 'SARENA'), ('Ljubicasta', 'LJUBICASTA'), ('Zelena', 'Zelena')], default='Zelena', max_length=20),
        ),
    ]
