# Generated by Django 4.0.4 on 2022-11-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akcija',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('procenat', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='botanicki_naziv',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='brzina_rasta',
            field=models.CharField(choices=[('50-100cm', '50-100cm'), ('100cm +', '100cm +'), ('0-50cm', '0-50cm')], default='0-50cm', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='hesteg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='orezivanje',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='prezimljava',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='privlaci_insekte',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='velicina_slanja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vreme_cvetanja',
            field=models.CharField(choices=[('Januar', 'Januar'), ('FEBRUAR', 'FEBRUAR'), ('MART', 'MART'), ('DECEMBAR', 'DECEMBAR')], default='DECEMBAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='name',
            field=models.CharField(choices=[('Cetinar', 'Cetinar'), ('Liscar', 'Liscar'), ('Zbun', 'Zbun'), ('Ukrasno zbunje', 'Ukrasno zbunje'), ('Puzavica', 'Puzavica'), ('Penjacica', 'Penjacica'), ('Zacinsko i lekovito bilje', 'Zacinsko i lekovito bilje'), ('Bobicasto voce i povrce', 'Bobicasto voce i povrce'), ('Drvece', 'Drvece'), ('Oziljenje reznice', 'Oziljenje reznice'), ('Sobno cvece', 'Sobno cvece'), ('Ukrasne trave', 'Ukrasne trave'), ('Biljke za kamenjare', 'Biljke za kamenjare'), ('Topijari', 'Topijari'), ('Trajnica', 'Trajnica')], default='Trajnica', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Crna', 'CRNA'), ('Plava', 'PLAVA'), ('Roza', 'ROZA'), ('Crvena', 'CRVENA'), ('Sarena', 'SARENA'), ('Ljubicasta', 'LJUBICASTA'), ('Zelena', 'Zelena')], default='Zelena', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='flowering_time',
            field=models.CharField(choices=[('SUNCE', 'SUNCE'), ('POLUSENKA', 'POLUSENKA'), ('HLAD', 'HLAD')], default='HLAD', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='high',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='place_of_planting',
            field=models.CharField(choices=[('SAKSIJA', 'SAKSIJA'), ('ZARDINJERA', 'ZARDINJERA'), ('BASTA', 'BASTA'), ('OGRADA', 'OGRADA'), ('VISECA SAKSIJA', 'VISECA SAKSIJA'), ('POLUSENKA', 'POLUSENKA'), ('VECA SAKSIJA', 'VECA SAKSIJA')], default='VECA SAKSIJA', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_plant',
            field=models.CharField(choices=[('ZIMZELANA', 'ZIMZELANA'), ('LISTOPADNA', 'LISTOPADNA')], default='LISTOPADNA', max_length=50),
        ),
    ]
