# Generated by Django 4.0.4 on 2022-11-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_akcija_rename_brand_product_botanicki_naziv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flowering_time',
            new_name='mesto_sadnje',
        ),
        migrations.AddField(
            model_name='product',
            name='sirina_biljke',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brzina_rasta',
            field=models.CharField(choices=[('BRZORASTUCE', 'BRZORASTUCE'), ('SREDNJERASTUCE', 'SREDNJERASTUCE'), ('SPORORASTUCE', 'SPORORASTUCE')], default='SPORORASTUCE', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Crna', 'CRNA'), ('BELA', 'BELA'), ('BEZ', 'BEZ'), ('ZUTA', 'ZUTA'), ('ZLATNA', 'ZLATNA'), ('LILA', 'LILA'), ('NARANDZASTA', 'NARANDZASTA'), ('PURPURNA', 'PURPURNA'), ('RUZICASTA', 'RUZICASTA'), ('SIVA', 'SIVA'), ('BRAON', 'BRAON'), ('SARENA', 'SARENA'), ('PLAVA', 'PLAVA'), ('ROZA', 'ROZA'), ('CRVENA', 'CRVENA'), ('LJUBICASTA', 'LJUBICASTA'), ('ZELENA', 'ZELENA')], default='ZELENA', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='prezimljava',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vreme_cvetanja',
            field=models.CharField(choices=[('Januar', 'Januar'), ('FEBRUAR', 'FEBRUAR'), ('MART', 'MART'), ('APRIL', 'APRIL'), ('MAJ', 'MAJ'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AVGUST', 'AVGUST'), ('SEPTEMBAR', 'SEPTEMBAR'), ('OKTOBAR', 'OKTOBAR'), ('NOVEMBAR', 'NOVEMBAR'), ('DECEMBAR', 'DECEMBAR')], default='DECEMBAR', max_length=50),
        ),
    ]
