# Generated by Django 4.0.4 on 2022-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='countInStock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
