# Generated by Django 4.0.4 on 2023-02-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_product_image_plantimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantimage',
            old_name='project',
            new_name='product',
        ),
    ]
