# Generated by Django 4.0.4 on 2023-02-03 00:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_project_plantimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vre_cve',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('JANUAR', 'JANUAR'), ('FEBRUAR', 'FEBRUAR'), ('MART', 'MART'), ('APRIL', 'APRIL'), ('MAJ', 'MAJ')], default='MAJ', max_length=29),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='vreme_cvetanja',
            field=models.CharField(choices=[('JANUAR', 'JANUAR'), ('FEBRUAR', 'FEBRUAR'), ('MART', 'MART'), ('APRIL', 'APRIL'), ('MAJ', 'MAJ'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AVGUST', 'AVGUST'), ('SEPTEMBAR', 'SEPTEMBAR'), ('OKTOBAR', 'OKTOBAR'), ('NOVEMBAR', 'NOVEMBAR'), ('DECEMBAR', 'DECEMBAR')], default='DECEMBAR', max_length=50),
        ),
    ]
