# Generated by Django 4.0.4 on 2023-02-03 00:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_product_vre_cve_alter_product_vreme_cvetanja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vreme_cvetanja',
        ),
        migrations.AlterField(
            model_name='product',
            name='vre_cve',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('JANUAR', 'JANUAR'), ('FEBRUAR', 'FEBRUAR'), ('MART', 'MART'), ('APRIL', 'APRIL'), ('MAJ', 'MAJ'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AVGUST', 'AVGUST'), ('SEPTEMBAR', 'SEPTEMBAR'), ('OKTOBAR', 'OKTOBAR'), ('NOVEMBAR', 'NOVEMBAR'), ('DECEMBAR', 'DECEMBAR')], max_length=80),
        ),
    ]
