# Generated by Django 4.0.4 on 2023-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_product_vreme_cvetanja_alter_product_vre_cve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='botanicki_naziv',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brzina_rasta',
            field=models.CharField(choices=[('BRZORASTUCE', 'BRZORASTUCE'), ('SREDNJERASTUCE', 'SREDNJERASTUCE'), ('SPORORASTUCE', 'SPORORASTUCE')], default='SPORORASTUCE', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='hesteg',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='high',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mesto_sadnje',
            field=models.CharField(choices=[('SUNCE', 'SUNCE'), ('POLUSENKA', 'POLUSENKA'), ('HLAD', 'HLAD')], default='HLAD', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='orezivanje',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='place_of_planting',
            field=models.CharField(choices=[('SAKSIJA', 'SAKSIJA'), ('ZARDINJERA', 'ZARDINJERA'), ('BASTA', 'BASTA'), ('OGRADA', 'OGRADA'), ('VISECA SAKSIJA', 'VISECA SAKSIJA'), ('POLUSENKA', 'POLUSENKA'), ('VECA SAKSIJA', 'VECA SAKSIJA')], default='VECA SAKSIJA', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='prezimljava',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='privlaci_insekte',
            field=models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='sirina_biljke',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_plant',
            field=models.CharField(choices=[('ZIMZELANA', 'ZIMZELANA'), ('LISTOPADNA', 'LISTOPADNA')], default='LISTOPADNA', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='velicina_slanja',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
