# Generated by Django 4.0.4 on 2023-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_product_botanicki_naziv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='base.plantcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Crna', 'CRNA'), ('BELA', 'BELA'), ('BEZ', 'BEZ'), ('ZUTA', 'ZUTA'), ('ZLATNA', 'ZLATNA'), ('LILA', 'LILA'), ('NARANDZASTA', 'NARANDZASTA'), ('PURPURNA', 'PURPURNA'), ('RUZICASTA', 'RUZICASTA'), ('SIVA', 'SIVA'), ('BRAON', 'BRAON'), ('SARENA', 'SARENA'), ('PLAVA', 'PLAVA'), ('ROZA', 'ROZA'), ('CRVENA', 'CRVENA'), ('LJUBICASTA', 'LJUBICASTA'), ('ZELENA', 'ZELENA')], default='ZELENA', max_length=250),
        ),
    ]
