# Generated by Django 4.0.4 on 2023-02-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_product_category_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='name',
            field=models.CharField(choices=[('Cetinar', 'Cetinar'), ('Liscar', 'Liscar'), ('Zbun', 'Zbun'), ('Ukrasno zbunje', 'Ukrasno zbunje'), ('Puzavica', 'Puzavica'), ('Penjacica', 'Penjacica'), ('Zacinsko i lekovito bilje', 'Zacinsko i lekovito bilje'), ('Bobicasto voce i povrce', 'Bobicasto voce i povrce'), ('Drvece', 'Drvece'), ('Oziljenje reznice', 'Oziljenje reznice'), ('Sobno cvece', 'Sobno cvece'), ('Ukrasne trave', 'Ukrasne trave'), ('Biljke za kamenjare', 'Biljke za kamenjare'), ('Topijari', 'Topijari'), ('Trajnica', 'Trajnica')], default='Trajnica', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
