# Generated by Django 4.0.4 on 2023-02-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_plantcategory_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='base.plantcategory'),
        ),
    ]
