# Generated by Django 4.0.4 on 2023-02-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='name',
            field=models.CharField(choices=[('Trajnice-perene', 'Trajnice-perene'), ('Penjacice', 'Penjacice'), ('Puzavice', 'Puzavice'), ('Ukrasno zbunje', 'Ukrasno zbunje'), ('Zacinsko i lekovito bilje', 'Zacinsko i lekovito bilje'), ('Ukrasne trave', 'Ukrasne trave'), ('Sedumi i cuvarkuce', 'Sedumi i cuvarkuce'), ('Liscari', 'Liscari'), ('Cetinari', 'Cetinari'), ('Ruze', 'Ruze'), ('Sadnice voca', 'Sadnice voca'), ('Ostalo', 'Ostalo')], default='Ostalo', max_length=50, unique=True),
        ),
    ]
