# Generated by Django 4.0.4 on 2023-02-07 15:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isporuka',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sirina',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brzina_rasta',
            field=models.CharField(choices=[('brzorastuće', 'brzorastuće'), ('srednje brzine', 'srednje brzine'), ('spororastuće', 'spororastuće')], default='spororastuće', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='mesto_sadnje',
            field=models.CharField(choices=[('sunce', 'sunce'), ('polusenka', 'polusenka'), ('hlad', 'hlad')], default='hlad', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='orezivanje',
            field=models.CharField(choices=[('da', 'da'), ('ne', 'ne')], default='ne', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='privlaci_insekte',
            field=models.CharField(choices=[('da', 'da'), ('ne', 'ne')], default='ne', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_plant',
            field=models.CharField(choices=[('zimzelena', 'zimzelena'), ('listopadna', 'listopadna'), ('višegodišnja', 'višegodišnja'), ('delimično zimzelena', 'delimično zimzelena')], default='delimično zimzelena', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='vre_cve',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('januar', 'januar'), ('februar', 'februar'), ('mart', 'mart'), ('april', 'april'), ('maj', 'maj'), ('jun', 'jun'), ('jul', 'jul'), ('avgust', 'avgust'), ('septembar', 'septembar'), ('oktobar', 'oktobar'), ('novembar', 'novembar'), ('decembar', 'decembar')], max_length=80),
        ),
    ]
