# Generated by Django 4.0.4 on 2023-02-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_product_isporuka_product_sirina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isporuka',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sirina',
        ),
    ]
