# Generated by Django 4.0.4 on 2023-02-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_product_isporuka_remove_product_sirina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcategory',
            name='name',
            field=models.CharField(choices=[('Trajnice-perene', 'Trajnice-perene'), ('Penjačice', 'Penjačice'), ('Puzavice', 'Puzavice'), ('Ukrasno žbunje', 'Ukrasno žbunje'), ('Začinsko i lekovito bilje', 'Začinsko i lekovito bilje'), ('Ukrasne trave', 'Ukrasne trave'), ('Sedumi i čuvarkuće', 'Sedumi i čuvarkuće'), ('Lišćari', 'Lišćari'), ('Četinari', 'Četinari'), ('Ruže', 'Ruže'), ('Sadnice voca', 'Sadnice voca'), ('Ostalo', 'Ostalo')], default='Ostalo', max_length=50, unique=True),
        ),
    ]
