# Generated by Django 4.0.4 on 2023-02-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_plantcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
