# Generated by Django 4.0.4 on 2023-02-28 15:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_plantimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mesto_sadnje',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sunce', 'sunce'), ('polusenka', 'polusenka'), ('hlad', 'hlad')], max_length=20),
        ),
    ]
