# Generated by Django 4.0.4 on 2023-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_plantcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brzina_rasta',
            field=models.CharField(choices=[('', ''), ('brzorastuće', 'brzorastuće'), ('srednje brzine', 'srednje brzine'), ('spororastuće', 'spororastuće')], default='spororastuće', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='orezivanje',
            field=models.CharField(choices=[('', ''), ('da', 'da'), ('ne', 'ne')], default='ne', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='privlaci_insekte',
            field=models.CharField(choices=[('', ''), ('da', 'da'), ('ne', 'ne')], default='ne', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_plant',
            field=models.CharField(choices=[('', ''), ('zimzelena', 'zimzelena'), ('listopadna', 'listopadna'), ('višegodišnja', 'višegodišnja'), ('delimično zimzelena', 'delimično zimzelena')], default='delimično zimzelena', max_length=250),
        ),
    ]
