# Generated by Django 4.0.4 on 2023-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_product_brzina_rasta_alter_product_orezivanje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcategory',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='name',
            field=models.CharField(choices=[('Trajnice-perene', 'Trajnice-perene'), ('Penjačice i Puzavice', 'Penjačice i Puzavice'), ('Ukrasno žbunje', 'Ukrasno žbunje'), ('Začinsko i aromatično bilje', 'Začinsko i aromatično bilje'), ('Ukrasne trave', 'Ukrasne trave'), ('Sedumi i čuvarkuće', 'Sedumi i čuvarkuće'), ('Lišćari', 'Lišćari'), ('Četinari', 'Četinari'), ('Biljke za hlad', 'Biljke za hlad'), ('Sadnice voća', 'Sadnice voća'), ('Proizvodi na akciji', 'Proizvodi na akciji'), ('Ostalo', 'Ostalo')], default='Ostalo', max_length=50, unique=True),
        ),
    ]
