# Generated by Django 4.0.4 on 2023-03-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_plantcategory_order_alter_plantcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='novo',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='popust',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prodajno_mesto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
