# Generated by Django 4.0.4 on 2023-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_product_novo_product_popust_product_prodajno_mesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='novo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='popust',
            field=models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=3, null=True),
        ),
    ]
