# Generated by Django 4.0.4 on 2023-03-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_product_novo_alter_product_popust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popust',
            field=models.CharField(blank=True, choices=[('0', '0'), ('10', '10'), ('20', '20'), ('30', '30')], max_length=3, null=True),
        ),
    ]
